/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.afarcloud.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum Priority implements org.apache.thrift.TEnum {
  UNDEFINED(0),
  LOW(1),
  HIGH(2);

  private final int value;

  private Priority(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static Priority findByValue(int value) { 
    switch (value) {
      case 0:
        return UNDEFINED;
      case 1:
        return LOW;
      case 2:
        return HIGH;
      default:
        return null;
    }
  }
}
