@startuml

title __UPPAALPLANNER's Class Diagram__\n

  namespace com.swarms.thrift {
    class com.swarms.thrift.Action {
    }
  }
  

  namespace com.swarms.thrift {
    class com.swarms.thrift.Capability {
    }
  }
  

  namespace com.swarms.thrift {
    class com.swarms.thrift.Current {
    }
  }
  

  namespace com.swarms.thrift {
    class com.swarms.thrift.Equipment {
    }
  }
  

  namespace com.swarms.thrift {
    enum EquipmentType {
    }
  }
  

  namespace com.swarms.thrift {
    class com.swarms.thrift.Event {
    }
  }
  

  namespace com.swarms.thrift {
    class com.swarms.thrift.H2S {
    }
  }
  

  namespace com.swarms.thrift {
    class com.swarms.thrift.Landmark {
    }
  }
  

  namespace com.swarms.thrift {
    class com.swarms.thrift.Mission {
    }
  }
  

  namespace com.swarms.thrift {
    class com.swarms.thrift.MmtService {
    }
  }
  

  namespace com.swarms.thrift {
    class com.swarms.thrift.MtrrService {
    }
  }
  

  namespace com.swarms.thrift {
    class com.swarms.thrift.Orientation {
    }
  }
  

  namespace com.swarms.thrift {
    class com.swarms.thrift.Ph {
    }
  }
  

  namespace com.swarms.thrift {
    class com.swarms.thrift.PlannerService {
    }
  }
  

  namespace com.swarms.thrift {
    class com.swarms.thrift.Position {
    }
  }
  

  namespace com.swarms.thrift {
    class com.swarms.thrift.Pressure {
    }
  }
  

  namespace com.swarms.thrift {
    class com.swarms.thrift.Region {
    }
  }
  

  namespace com.swarms.thrift {
    class com.swarms.thrift.Salinity {
    }
  }
  

  namespace com.swarms.thrift {
    class com.swarms.thrift.SelectionService {
    }
  }
  

  namespace com.swarms.thrift {
    class com.swarms.thrift.SemanticQueryService {
    }
  }
  

  namespace com.swarms.thrift {
    class com.swarms.thrift.Task {
    }
  }
  

  namespace com.swarms.thrift {
    enum TaskRegionType {
    }
  }
  

  namespace com.swarms.thrift {
    enum TaskStatus {
    }
  }
  

  namespace com.swarms.thrift {
    class com.swarms.thrift.Temperature {
    }
  }
  

  namespace com.swarms.thrift {
    class com.swarms.thrift.TimedSpeed {
    }
  }
  

  namespace com.swarms.thrift {
    class com.swarms.thrift.Vehicle {
    }
  }
  

  namespace com.swarms.thrift {
    enum VehicleType {
    }
  }
  

  namespace midware {
    class midware.PlannerServiceHandler {
    }
  }
  

  namespace midware {
    class midware.UPlanner {
    }
  }
  

  com.swarms.thrift.Action .up.|> java.io.Serializable
  com.swarms.thrift.Action .up.|> java.lang.Cloneable
  com.swarms.thrift.Action .up.|> java.lang.Comparable
  com.swarms.thrift.Action .up.|> org.apache.thrift.TBase
  com.swarms.thrift.Action o-- com.swarms.thrift.Region : area
  com.swarms.thrift.Action o-- com.swarms.thrift.Orientation : bearing
  com.swarms.thrift.Action o-- com.swarms.thrift.Task : relatedTask
  com.swarms.thrift.Action o-- com.swarms.thrift.TaskStatus : status
  com.swarms.thrift.Capability .up.|> java.io.Serializable
  com.swarms.thrift.Capability .up.|> java.lang.Cloneable
  com.swarms.thrift.Capability .up.|> java.lang.Comparable
  com.swarms.thrift.Capability .up.|> org.apache.thrift.TBase
  com.swarms.thrift.Current .up.|> java.io.Serializable
  com.swarms.thrift.Current .up.|> java.lang.Cloneable
  com.swarms.thrift.Current .up.|> java.lang.Comparable
  com.swarms.thrift.Current .up.|> org.apache.thrift.TBase
  com.swarms.thrift.Equipment .up.|> java.io.Serializable
  com.swarms.thrift.Equipment .up.|> java.lang.Cloneable
  com.swarms.thrift.Equipment .up.|> java.lang.Comparable
  com.swarms.thrift.Equipment .up.|> org.apache.thrift.TBase
  com.swarms.thrift.Equipment o-- com.swarms.thrift.EquipmentType : type
  com.swarms.thrift.EquipmentType .up.|> org.apache.thrift.TEnum
  com.swarms.thrift.Event .up.|> java.io.Serializable
  com.swarms.thrift.Event .up.|> java.lang.Cloneable
  com.swarms.thrift.Event .up.|> java.lang.Comparable
  com.swarms.thrift.Event .up.|> org.apache.thrift.TBase
  com.swarms.thrift.H2S .up.|> java.io.Serializable
  com.swarms.thrift.H2S .up.|> java.lang.Cloneable
  com.swarms.thrift.H2S .up.|> java.lang.Comparable
  com.swarms.thrift.H2S .up.|> org.apache.thrift.TBase
  com.swarms.thrift.Landmark .up.|> java.io.Serializable
  com.swarms.thrift.Landmark .up.|> java.lang.Cloneable
  com.swarms.thrift.Landmark .up.|> java.lang.Comparable
  com.swarms.thrift.Landmark .up.|> org.apache.thrift.TBase
  com.swarms.thrift.Mission .up.|> java.io.Serializable
  com.swarms.thrift.Mission .up.|> java.lang.Cloneable
  com.swarms.thrift.Mission .up.|> java.lang.Comparable
  com.swarms.thrift.Mission .up.|> org.apache.thrift.TBase
  com.swarms.thrift.Mission o-- com.swarms.thrift.Region : navigationArea
  com.swarms.thrift.Orientation .up.|> java.io.Serializable
  com.swarms.thrift.Orientation .up.|> java.lang.Cloneable
  com.swarms.thrift.Orientation .up.|> java.lang.Comparable
  com.swarms.thrift.Orientation .up.|> org.apache.thrift.TBase
  com.swarms.thrift.Ph .up.|> java.io.Serializable
  com.swarms.thrift.Ph .up.|> java.lang.Cloneable
  com.swarms.thrift.Ph .up.|> java.lang.Comparable
  com.swarms.thrift.Ph .up.|> org.apache.thrift.TBase
  com.swarms.thrift.Position .up.|> java.io.Serializable
  com.swarms.thrift.Position .up.|> java.lang.Cloneable
  com.swarms.thrift.Position .up.|> java.lang.Comparable
  com.swarms.thrift.Position .up.|> org.apache.thrift.TBase
  com.swarms.thrift.Pressure .up.|> java.io.Serializable
  com.swarms.thrift.Pressure .up.|> java.lang.Cloneable
  com.swarms.thrift.Pressure .up.|> java.lang.Comparable
  com.swarms.thrift.Pressure .up.|> org.apache.thrift.TBase
  com.swarms.thrift.Region .up.|> java.io.Serializable
  com.swarms.thrift.Region .up.|> java.lang.Cloneable
  com.swarms.thrift.Region .up.|> java.lang.Comparable
  com.swarms.thrift.Region .up.|> org.apache.thrift.TBase
  com.swarms.thrift.Salinity .up.|> java.io.Serializable
  com.swarms.thrift.Salinity .up.|> java.lang.Cloneable
  com.swarms.thrift.Salinity .up.|> java.lang.Comparable
  com.swarms.thrift.Salinity .up.|> org.apache.thrift.TBase
  com.swarms.thrift.Salinity o-- com.swarms.thrift.Position : position
  com.swarms.thrift.Task .up.|> java.io.Serializable
  com.swarms.thrift.Task .up.|> java.lang.Cloneable
  com.swarms.thrift.Task .up.|> java.lang.Comparable
  com.swarms.thrift.Task .up.|> org.apache.thrift.TBase
  com.swarms.thrift.Task o-- com.swarms.thrift.TaskRegionType : regionType
  com.swarms.thrift.TaskRegionType .up.|> org.apache.thrift.TEnum
  com.swarms.thrift.TaskStatus .up.|> org.apache.thrift.TEnum
  com.swarms.thrift.Temperature .up.|> java.io.Serializable
  com.swarms.thrift.Temperature .up.|> java.lang.Cloneable
  com.swarms.thrift.Temperature .up.|> java.lang.Comparable
  com.swarms.thrift.Temperature .up.|> org.apache.thrift.TBase
  com.swarms.thrift.TimedSpeed .up.|> java.io.Serializable
  com.swarms.thrift.TimedSpeed .up.|> java.lang.Cloneable
  com.swarms.thrift.TimedSpeed .up.|> java.lang.Comparable
  com.swarms.thrift.TimedSpeed .up.|> org.apache.thrift.TBase
  com.swarms.thrift.Vehicle .up.|> java.io.Serializable
  com.swarms.thrift.Vehicle .up.|> java.lang.Cloneable
  com.swarms.thrift.Vehicle .up.|> java.lang.Comparable
  com.swarms.thrift.Vehicle .up.|> org.apache.thrift.TBase
  com.swarms.thrift.Vehicle o-- com.swarms.thrift.Position : location
  com.swarms.thrift.Vehicle o-- com.swarms.thrift.Orientation : orientation
  com.swarms.thrift.Vehicle o-- com.swarms.thrift.VehicleType : type
  com.swarms.thrift.VehicleType .up.|> org.apache.thrift.TEnum
  midware.PlannerServiceHandler .up.|> com.swarms.thrift.PlannerService.Iface


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
